version: '3.8'

services:
  redis:
    image: redis
    restart: always
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
  mongo:
    image: mongo
    restart: always
    ports:
      - '${DB_PORT}:${DB_PORT}'
